### ISSUE TITLE
Prepifg - DEM file size

### ISSUE THREAD

**Issue by mcgarth** [GeoscienceAustralia/PyRate#143]
Full size Geotiffs for the DEM are Int16
Multi-looked Geotiffs for the DEM are Floats

Keep multi-looked Geotiffs as Int16?

**Comment by basaks** [comment]
This is fixed by 65dba77.

Also tested [here](https://github.com/GeoscienceAustralia/PyRate/blob/develop/tests/test_prepifg.py#L362) and [here](https://github.com/GeoscienceAustralia/PyRate/blob/develop/tests/test_prepifg.py#L350)
