### ISSUE TITLE
implement multiprocess orbfit2

### ISSUE THREAD

**Issue by basaks** [GeoscienceAustralia/PyRate#147]
The current implementation of [orbfit method 2 (network correction)](https://github.com/GeoscienceAustralia/PyRate/blob/3ead788a61987950323cd9782b38bf8d9e113bef/pyrate/orbital.py#L193) has the following features:

- In memory multilooking using shared.Ifg class using a single process

- Currently the network correction method works using Ifg classes. Since we are using gdal infrastructure and work using gdal dataset objects (Ifg class) that don't communicate across processes. We are forced to use single process if we use in memory Ifg class instances.

There are two ways to improve efficiency:
1. Continue using Ifg class, but write multilooked datasets on disc and reread them during network correction method. This involves a little less work as the [get_design_matrix](https://github.com/GeoscienceAustralia/PyRate/blob/3ead788a61987950323cd9782b38bf8d9e113bef/pyrate/orbital.py#L329) function will not have to be modified.
2. A better approach (and most efficient) is to continue to use in memory multilooking, use many processes to do in memory multilooking, and pass just the the phase data instead to a single process for design matrix and least squares orbital fit parameter estimation. This will require a minor modification of the [design matrix function](https://github.com/GeoscienceAustralia/PyRate/blob/3ead788a61987950323cd9782b38bf8d9e113bef/pyrate/orbital.py#L329). Then this will enable us to perform multilooking using many processes, in memory operations, not require a lot of read/write operation of multilooked ifgs.

[All of these should be referred to this version in the repo.](https://github.com/GeoscienceAustralia/PyRate/tree/3ead788a61987950323cd9782b38bf8d9e113bef)

**Comment by mcgarth** [comment]
Do you have an estimate of the time to implement either option 1 or option 2?

Option 2 sounds better but benchmarking may reveal it is not really necessary

**Comment by basaks** [comment]
>> Do you have an estimate of the time to implement either option 1 or option 2?

One day? May be 1.5.

>> Option 2 sounds better but benchmarking may reveal it is not really necessary

Add another day for 2 days total.
Both estimates include writing appropriate tests.

**Comment by basaks** [comment]
Postponed for now. Assinged to @mcgarth .

**Comment by mcgarth** [comment]
Closing, but referenced in Issue #75
