### ISSUE TITLE
BUG: MPI jobs across multiple nodes crash

### ISSUE THREAD

**Issue by mcgarth** [GeoscienceAustralia/PyRate#151]
Whilst running some benchmarks for prepifg I submitted a job to the broadwell queue that spans multiple nodes. Here are the stats:

ifgs to be converted = 131
cpu request = 56 (2 nodes)
mem request = 512 Gb (2 nodes)

This job failed with exit status 1. Please see attached error log.

The curious thing is that all 131 interferograms were converted to geotiff and multi-looked successfully.

Is this an issue with idle nodes? Or perhaps it's related to the Allinea profiling software I am using?

[pbs.script.o2994703.txt](https://github.com/GeoscienceAustralia/PyRate/files/832933/pbs.script.o2994703.txt)
[pbs.script.e2994703.txt](https://github.com/GeoscienceAustralia/PyRate/files/832932/pbs.script.e2994703.txt)

**Comment by mcgarth** [comment]
Not an issue with idle nodes. Got the same error for a job with 140 cpus and 1280 Gb

**Comment by basaks** [comment]
Can you please give me the location of this job? 
Yes, may be turn off profiling to make sure it's not the profiler.

**Comment by mcgarth** [comment]
/short/dg9/insar/PyRate_Medium_test

It's likely to be the profiler. Just checking the same job without Allinea enabled

**Comment by mcgarth** [comment]
Indeed - an issue with the Allinea profile. The job I ran with Allinea disabled ran without issue.

I will ask NCI for assistance.

**Comment by mcgarth** [comment]
Retested the original problem today (as stated in first comment) without Allinea profiler and commit https://github.com/GeoscienceAustralia/PyRate/commit/ba00aeacc2aa1190991de1001d53a01f0680a109 - it works :-D
