### ISSUE TITLE
time series svd code not tested

### ISSUE THREAD

**Issue by basaks** [GeoscienceAustralia/PyRate#154]

**Comment by basaks** [comment]
Sctually it is tested here: https://github.com/GeoscienceAustralia/PyRate/blob/master/tests/test_timeseries.py#L239

I will investigate why we have a mismatch in the current config I am testing.

**Comment by basaks** [comment]
Found the culprit why matlab tlpfilter output did not matach with pythons's :)

In the matlab config file, the parameter `tlpfpthr` is set, but not use. Instead `tlpfpthr` is reassinged to `pthr` for some reason. 

Now the outputs matach as can be seen in e7532174b5c0ebc7285cc9b6ecf00fe9536b0874.

**Comment by mcgarth** [comment]
Good pick up. So if it was to do with the pthr the issue would have been for pixels that had more nans through time that were failing. From my recollection of the test data these culprit pixels are near the centre of the image.

@basaks close if you're happy
