### ISSUE TITLE
Document Review Results

### ISSUE THREAD

**Issue by lawrie26** [GeoscienceAustralia/PyRate#160]
Reviewed documentation associated with PyRate in preparation for external user testing and release. Each script has been reviewed to ensure there is an appropriate brief description, parameters described and return results listed. 

Appears to be a issue with how the auto generated webpages are being produced. There is some mis-match between the webpages and scripts. Re-generating the updated webpages may solve some of the issues listed.

Changes made in branch 'sarah-dev'. This is a copy of the development branch.

Identified issues:

- [x]  Clarify if ``linrate`` was split into two parts, eg ``correct`` and ``linrate_timeseries``, as discussed in a meeting. If so, need documentation updated/created to reflect this.
MG: keep as 3 steps for now. ``correct`` step not implemented in code
- [x]  Check if scripts ``PyRate/pyrate/compat.py`` and ``PyRate/pyrate/mpiops.py`` should be considered modules and added to auto generated webpages
MG: compat.py - No; mpiops.py - Yes
- [x]  Check if scripts under ``PyRate/pyrate/tasks/`` should have documentation
MG: we should try to document this functionality (LUIGI)
- [x]  Check if scripts under ``PyRate/utils/`` should have documentation
MG: its good practice but not a formal requirement at this time
- [x]  Check if test scripts should have documentation
MG: its good practice but not a formal requirement at this time

``PyRate/pyrate/algorithm.py``
- [x]  ``is_square`` needs return results
- [x]  ``least_squares_covariance`` needs return results
- [x]  ``los_conversion`` needs a brief description
- [x]  ``unit_vector`` needs brief and parameter descriptions
- [x]  ``ifg_date_lookup`` needs return results
- [x]  ``ifg_date_index_lookup`` needs return results
- [x]  ``get_epochs`` needs return results
- [x]  ``get_all_epochs`` needs return results
- [x]  ``master_slave_ids`` needs return results

``PyRate/pyrate/aps.py`` 
- [x]  When updated function is complete, need to check descriptions, parameters, return values.

``PyRate/pyrate/config.py``: 
- [x]  Remove reference to PyAPS ``handle_pyaps_parameters``
- [x]  ``DEM_FILE`` description is correct in script, but not in auto generated webpage
SL: auto fixed with doco update
- [x]  ``INPUT_IFG_PROJECTION`` description extra sentence appearing in auto generated webpage, script has a second line (line 55) which appears to be unfinished
- [x]  ``NAN_CONVERSION`` auto generated webpage has description as 'todo', but a valid description is in script
SL: auto fixed with doco update
- [x]  ``OBS_DIR`` description has an extra sentence appearing in auto generated webpage
- [x]  Only one line of the description is showing in auto generated webpage. Check if script changes (addition of :) fix this:
        2 lines of description: 
               ``LR_PTHRESH``
               ``ORBITAL_FIT``
               ``ORBITAL_FIT_METHOD``
               ``REFX``
               ``REFY``
               ``REF_MIN_FRAC``
               ``TIME_SERIES_PTHRESH``
               ``TIME_SERIES_SM_FACTOR``
               ``TIME_SERIES_SM_ORDER``
         3 lines of description: 
               ``IFG_CROP_OPT``
               ``ORBITAL_FIT_DEGREE``
         4 lines of description: 
               ``LR_NSIG``
- [x]  Need descriptions added to script and auto generated webpage:
              ``APS_CORRECTION``
              ``APS_ELEVATION_EXT`` 
              ``APS_ELEVATION_MAP`` 
              ``APS_INCIDENCE_EXT`` 
              ``APS_INCIDENCE_MAP`` 
              ``APS_METHOD`` 
- [x]  Clarify what's the difference between the orbital parameters (line 114) and the orbital constants (line 
167)? 
- [x]  Missing from auto generated webpage but in script:
             ``LUIGI``
             ``REF_EST_METHOD``
             ``SLC_DIR``
             ``TMPDIR``
SL: auto fixed with doco update
- [x]  On auto generated webpage as 'not currently used', but missing from script:
             ``AMPLITUDE_FLAG``
             ``PERP_BASELINE_FLAG``
             ``SIM_DIR``
SL: auto fixed with doco update
-  [x]  On auto generated webpage, but missing from script:
             ``ROIPAC_RESOURCE_HEADER``
SL: auto fixed with doco update
- [x]  ``degree_conv`` needs parameter description and return results
- [x]  ``method_conv`` needs parameter description and return results
- [x]  ``get_config_params`` needs parameter description and return results
- [x]  ``parse_namelist`` needs parameter description and return results
- [x]  ``write_config_file`` needs parameter description and return results
- [x]  ``reverse_degree_conv`` needs parameter description and return results
- [x]  ``transform_params`` needs parameter description and return results
- [x]  ``original_ifg_paths`` needs parameter description and return results
- [x]  ``mlooked_path`` needs parameter description and return results
- [x]  ``get_dest_paths`` needs a brief description
- [x]  ``get_ifg_paths`` needs a brief description

``PyRate/pyrate/gamma.py`` 
- [x]  ``check_raw_data`` needs a brief description and return results
- [x]  ``check_step_mismatch`` needs a brief description and return results
- [x]  ``parse_header`` needs parameter description and return results
- [x]  ``parse_epoch_header`` needs parameter description and return results
- [x]  ``parse_date_time`` needs parameter description and return results 
- [x]  ``parse_dem_header`` needs parameter description and return results 
- [x]  ``frequency_to_wavelength`` needs parameter description and return results 
- [x]  ``combine_headers`` needs return results 
- [x]  ``manage_headers`` needs a brief description 
- [x]  ``parse_header_new`` in auto generated webpage but not in script. MG: not existing in current module

``PyRate/pyrate/gdal_python.py`` 
- [x]  ``world_to_pixel`` needs parameter description and return results
- [x]  ``crop`` needs return results
- [x]  ``resample_nearest_neighbour`` needs parameter description and return results
- [x]  ``crop_rasample_setup`` needs parameter description and return results
- [x]  ``gdalwarp_width_and_height`` needs parameter description and return results
- [x]  ``crop_resample_average`` needs return results
- [x]  ``gdal_average`` needs brief description
- [x]  ``get_matlab_resampled_data_size`` needs parameter description and return results

``PyRate/pyrate/ifgconstants.py`` 
- [x]  Check if more documentation should be included in auto generated webpage
        MG: not necessary, these are just metadata labels

``PyRate/pyrate/linrate.py`` 
- [x]  ``linrate_setup`` needs parameter descriptions and return results
- [x]  ``linear_rate_by_rows`` needs parameter descriptions and return results
- [x]  ``linear_rate_by_pixel`` needs parameter descriptions and return results

``PyRate/pyrate/matlab_mst.py`` 
- [x]  ``reshape_n`` needs brief description
- [x]  ``update_nan_frac`` needs brief description
- [x]  ``convert_nans`` needs brief description
- [x]  ``make_data_stack`` needs brief description
- [x]  ``get_ifgs_list`` needs brief description
- [x]  ``get_nml_list`` needs brief description
- [x]  ``data_setup`` needs parameter descriptions and return results
- [x]  ``get_nml`` needs parameter descriptions and return results
- [x]  ``matlab_mst_kruskal`` needs return results
- [x]  ``calculate_connect_and_ntrees`` needs parameter descriptions and return results
- [x]  ``matlab_mst`` needs parameter descriptions and return results
- [x]  ``matlab_mst_gen`` needs return results
- [x]  ``matlab_mst_tool`` needs return results

``PyRate/pyrate/mst.py`` 
- [x]  ``mst_from_ifgs`` needs parameter descriptions and return results
- [x]  ``mst_parallel`` needs parameter descriptions and return results
- [x]  ``mst_multiprocessing`` needs parameter descriptions and return results
- [x]  ``mst_matrix_networkx`` needs return results
- [x]  ``minimum_spanning_from_mst`` needs brief description

``PyRate/pyrate/orbital.py`` 
- [x]  ``orbital_correction`` needs return results
- [x]  ``independent_correction`` clarify parameters ``offset`` and ``params`` as they only specify the input type, not what the input is, and needs return results
- [x]  ``network_correction`` return results
- [x]  ``_remove_networkx_error`` needs brief description
- [x]  ``get_design_matrix`` needs return results
- [x]  ``get_network_design_matrix`` needs return results
- [x]  ``remove_orbital_error`` needs return results

``PyRate/pyrate/prepifg.py`` 
- [x]  ``is_number`` needs parameter description and return results
- [x]  ``get_analysis_extent`` needs parameter description and return results
- [x]  ``prepare_ifg`` needs parameter description and return results
- [x]  ``dummy_warp`` needs parameter description and return results
- [x]  ``prepare_ifgs`` needs return results
- [x]  ``dem_or_ifg`` needs parameter description and return results
- [x]  ``get_extents`` needs parameter description and return results
- [x]  ``warp`` needs return results
- [x]  ``resample`` needs return results
- [x]  ``check_resolution`` needs parameter description and return results
- [x]  ``check_looks`` needs parameter description and return results
- [x]  ``min_bounds`` needs parameter description and return results
- [x]  ``max_bounds`` needs parameter description and return results
- [x]  ``get_same_bounds`` needs parameter description and return results
- [x]  ``custom_bounds`` needs parameter description and return results
- [x]  ``check_crop_coords`` needs parameter description and return results
- [x]  ``extents_from_params`` needs parameter description and return results

``PyRate/pyrate/pyratelog.py``
- [x]  ``configure`` needs return results

``PyRate/pyrate/ref_phs_est.py``
- [x]  ``estimate_ref_phase`` needs brief description
- [x]  Need to clarify the differences between method1 and method2 in the descriptions in the script
- [x]  ``est_ref_phs_method2`` needs parameter description and return results
- [x]  ``est_ref_phs_method1`` needs parameter description and return results
- [x]  ``check_ref_phase_ifgs`` needs parameter description and return results

``PyRate/pyrate/refpixel.py``
- [x]  On auto generated webpage, but marked as hidden from script:
             ``validate_chipsize``
             ``validate_minimum_fraction``
             ``validate_search_win``
SL: auto fixed with doco update
- [x]  ``ref_pixel`` needs return results
- [x]  ``ref_pixel_setup`` needs parameter description and return results
- [x]  ``ref_pixel_mpi`` needs parameter description and return results
- [x]  ``ref_pixel_multi`` needs parameter description and return results
- [x]  ``step`` needs return results

``PyRate/pyrate/roipac.py``
- [x]  ``check_raw_data`` needs brief description and return results
- [x]  ``check_step_mismatch`` needs brief description and return results
- [x]  ``parse_date`` needs parameter description and return results
- [x]  ``parse_header`` needs parameter description and return results
- [x]  ``_parse_dates_from`` needs brief description 
- [x]  ``manage_header`` needs brief parameter descriptions and return results

``PyRate/pyrate/shared.py``
- [x]  ``mkdir_p`` states 'copied from stackoverflow', needs a reference
- [x]  ``class RasterBase`` functions need brief descriptions
- [x]  ``class Ifg`` functions need brief descriptions
- [x]  ``class IfgPart`` functions need brief descriptions
- [x]  ``convert_to_nans`` refers to a parameter value in text, but no variable exists in function 
- [x]  ``convert_to_mm`` refers to a parameter value in text, but no variable exists in function 
- [x]  ``write_modified_phase`` brief description appears to be incomplete
- [x]  ``convert_radians_to_mm`` needs return results
- [x]  ``nanmedian`` needs brief and parameter descriptions, and return results
- [x]  ``write_geotiff`` needs parameter description and return results
- [x]  ``write_unw_from_data_or_geotiff`` needs brief description and return results
- [x]  ``write_output_geotiff`` needs parameter description and return results
- [x]  ``copytree`` needs parameter description and return results. MG: moved to tests/common
- [x]  ``pre_prepare_ifgs`` needs brief description. MG: moved to tests/common
- [x]  ``nan_and_mm_convert`` needs brief description and return results
- [x]  ``cell_size`` needs return results
- [x]  ``utm_zone`` needs parameter description and return results
- [x]  ``prepare_ifg`` needs brief description, lists 'tiles' as a parameter, but not listed in function
- [x]  ``save_numpy_phase`` needs return results
- [x]  ``get_projection_info`` needs return results
- [x]  ``warp_required`` parameters refer to 'x or y dir'. Is this directory or an actual value. Need clarification, and needs return results.

``PyRate/pyrate/timeseries.py``
- [x]  ``time_series_setup`` needs parameter description and return results
- [x]  ``time_series_by_row`` needs parameter description and return results
- [x]  ``remove_rank_def_rows`` needs parameter description and return results
- [x]  ``time_series_by_pixel`` needs parameter description and return results
- [x]  ``solve_ts_svd`` needs parameter description and return results
- [x]  ``plot_timeseries`` states a 'to do' action, needs parameter description and return results
- [x]  ``missing_option_error`` needs parameter description and return results

``PyRate/pyrate/covariance.py``
- [x]  ``pendiffexp`` needs return results
- [x]  ``cvd`` needs return results
- [x]  ``get_vcmt`` needs return results

``PyRate/pyrate/scripts/run_prepifg.py``
- [x]  ``main`` needs brief description and return results
- [x]  ``roipac_prepifg`` needs return results
- [x]  ``gamma_prepifg`` needs return results
- [x]  ``gamma_multiprocessing`` needs return results

``PyRate/pyrate/scripts/run_pyrate.py``
- [x]  ``_join_dicts`` needs brief description
- [x]  ``mst_calc`` needs return results
- [x]  ``save_ref_pixel_blocks`` needs brief description and return results. MG: moved to refpixel module
- [x]  ``orb_fit_calc`` needs return results
- [x]  ``ref_phase_estimation`` needs return results
- [x]  ``process_ifgs`` needs return results
- [x]  ``linrate_calc`` needs return results
- [x]  ``phase_sum`` needs return results
- [x]  ``timeseries_calc`` needs return results

``PyRate/pyrate/scripts/postprocessing.py``
- [x]  ``main`` needs parameter description and return results
- [x]  ``postprocess_linrate`` needs parameter description and return results
- [x]  ``save_linrate`` needs parameter description and return results
- [x]  ``postprocess_timeseries`` needs parameter description and return results

**Comment by mcgarth** [comment]
- Doco updated
- some code refactoring
- manual addition of changes from sarah-dev branch (which is now redundant) 

all merged into develop branch with PR #171 b87e4ef

**Comment by lawrie26** [comment]
after auto generating revised documentation, all outstanding issues have been resolved.
