### ISSUE TITLE
Accessing virtualenvwrapper on the NCI

### ISSUE THREAD

**Issue by lawrie26** [GeoscienceAustralia/PyRate#163]
Problems setting up virtualenv on the NCI when accessing virtualenvwrapper.

Can install virtualenv and virtualenvwrapper to a specific location on the NCI, but when modifying .profile with permanent path links and loading python 3.5.2 module, problems occur.

Setup in .profile:

`module load python3/3.5.2`
`module load python3/3.5.2-matplotlib`
`export PYTHONPATH=/g/data1/dg9/sll547/lib/python3.5/site-packages:$PYTHONPATH`
`export WORKON_HOME=/g/data1/dg9/sll547/venvs`

Error:

`/usr/bin/python: No module named virtualenvwrapper
virtualenvwrapper.sh: There was a problem running the initialization hooks.`

`If Python could not import the module virtualenvwrapper.hook_loader,
check that virtualenvwrapper has been installed for
VIRTUALENVWRAPPER_PYTHON=/usr/bin/python and that PATH is
set properly.`

Have tried to set the `VIRTUALENVWRAPPER_PYTHON` to point to different paths, but all fail. 

Have tried to continue creating the virtualenv, but it fails:

`mkvirtualenv -p python3 myenv`
`which: no virtualenv in (/apps/openmpi/wrapper/fortran:/apps/openmpi/wrapper:/apps/openmpi/1.6.3/bin:/apps/intel-ct/cc-wrapper:/apps/intel-ct/12.1.9.293/cc/bin/intel64:/apps/intel-ct/fc-wrapper/:/apps/intel-ct/12.1.9.293/fc/bin/intel64:/g/data1/dg9/sll547/pycharm-community-2016.3.3/bin:/apps/python3/3.5.2/bin:/opt/bin:/bin:/usr/bin:/opt/pbs/default/bin:.)
ERROR: virtualenvwrapper could not find virtualenv in your path`

Added location of virtualenv executable to PATH:

`export PATH=/g/data1/dg9/sll547/bin:$PATH`

New error:

`mkvirtualenv -p python3 myenv`
`Running virtualenv with interpreter /apps/python3/3.5.2/bin/python3`
`Using base prefix '/apps/python3/3.5.2'`
`New python executable in /g/data1/dg9/sll547/venvs/myenv/bin/python3`
`Also creating executable in /g/data1/dg9/sll547/venvs/myenv/bin/python`
`Installing setuptools, pip, wheel...done.`
`bash: /g/data1/dg9/sll547/lib/python3.5/site-packages/virtualenvwrapper/hook_loader.py: Permission denied`

Tried installation steps without using virtualenvwrapper, but got an error: `bash: mkvirtualenv: command not found`

**Comment by mcgarth** [comment]
When I set up my virtualenv on raijin I used the instructions at https://github.com/GeoscienceAustralia/PyRate/tree/master/pbs/README.rst 

In there is the following line:

`$ pip3 install  --user virtualenv virtualenvwrapper`

After executing this you should have the virtualenvwrapper.sh file located at `$HOME/.local/bin/virtualenvwrapper.sh` 

Can you confirm whether or not that is the case in your setup @lawrie26?

**Comment by lawrie26** [comment]
Resolved. The main page instructions didn't state to use the HPC instructions instead for NCI. Have been updated to reflect. this.
