### ISSUE TITLE
README for HPC states example scripts in pbs directory, but none exist

### ISSUE THREAD

**Issue by lawrie26** [GeoscienceAustralia/PyRate#164]
After moving the README from the pbs/ directory to a new hpc/ directory, the README refers to :

"In the pbs/ subfolder of the PyRate repository there are some example scripts to assist launching batch jobs over multiple nodes with PBS."

In moving the README, the pbs/ directory is now empty so it has been automatically deleted. 

Need to check find out if these example scripts exist, and if so, add them to the pbs/ directory.

**Comment by mcgarth** [comment]
I've been meaning to remove this statement about example scripts. 

There is no need for specific example scripts to be lodged in the `hpc/` dir since an example script is given at the bottom of the README file

**Comment by basaks** [comment]
@mcgarth @lawrie26 I have addressed this with PR #167, and also made some changes in the `readme` so that you don't get the mpi fork warning while submitting pbs jobs and some more minor changes.

Close when you are happy.
