### ISSUE TITLE
Consolidate Ref_phs_est code

### ISSUE THREAD

**Issue by mcgarth** [GeoscienceAustralia/PyRate#170]
A lot of reference phase estimation code from the ref_phs_est.py module is duplicated in the run_pyrate.py script. As a result the code in ref_phs_est.py is not used during the workflow and is basically useless.

- tests run on code in ref_phs_est.py
- code in run_pyrate.py is optimised for MPI
- code for the most part is nearly identical in the two locations

It would be ideal to build MPI functionality into ref_phs_est.py functions and deprecate those in run_pyrate.py

**Comment by brenmous** [comment]
Will fix this during this sprint as I do the prepifg/restructure branch refactoring.
