### ISSUE TITLE
Remove PYRATEPATH env variable

### ISSUE THREAD

**Issue by basaks** [GeoscienceAustralia/PyRate#176]
Can get any path using something similar to: https://github.com/GeoscienceAustralia/passive-seismic/blob/master/tests/test_convert_logs.py#L7

**Comment by brenmous** [comment]
@sheecegardezi I think you've solved this one?

**Comment by sheecegardezi** [comment]
PYRATEPATH replaced with finding abs path with os.path.dirname
[1c3cc3](https://github.com/GeoscienceAustralia/PyRate/commit/1c3cc3de624ac232e0f3b8cd33ed60fe4f9bae75)
