### ISSUE TITLE
Windows 10 support

### ISSUE THREAD

**Issue by Khalilsqu** [GeoscienceAustralia/PyRate#177]
Does this works in windows-10 OS.

**Comment by mcgarth** [comment]
Hi @Khalilsqu thanks for your interest in PyRate! Unfortunately Windows is not supported at this time, only linux/unix. If there is enough interest in Windows compatibility from the broader community we could potentially add that support in future development sprints.

**Comment by sheecegardezi** [comment]
Docker add for multiple platform support.  Please rfer to this guide for details:
https://geoscienceaustralia.github.io/PyRate/installation.html#docker

**Comment by mcgarth** [comment]
Reopening since Win10 compatibility of PyRate is still not implemented

**Comment by mcgarth** [comment]
We are recommending Widnows users to use Pyrate through Docker. Improved instructions for installing through Docker are available at https://geoscienceaustralia.github.io/PyRate/installation.html#docker 

In the fullness of time we may develop native support through Windows but there are many higher priorities at present.
