### ISSUE TITLE
mpi4py should be specified as required package in readme

### ISSUE THREAD

**Issue by mcvittal** [GeoscienceAustralia/PyRate#181]
PyRate would not install using pip unless mpi4py was installed through apt. This should be specified in the readme.

After mpi4py was installed, PyRate would install happily on both Python 2.7 and Python 3.6.7.

**Comment by mcgarth** [comment]
Hi Alex, thanks a lot for posting your feedback! Would you mind sharing the commands you used that resulted in the failed install (prior to installing mpi4py separately through apt)?

**Comment by brenmous** [comment]
The 0.3.0 release for Ubuntu 18.04 and NCI Raijin will work without this package. Mpi4py via apt installs Python bindings. These should be installed correctly if the required packages are installed (openmpi-bin and libopenmpi-dev - refer to utils/apt_install.sh) before running the pip install (or setup.py install locally). If this issue occurs again following the instructions for the new release please open a new issue and we'll work on it.
