### ISSUE TITLE
Sanity check "pthr" parameter for sensible value

### ISSUE THREAD

**Issue by mcgarth** [GeoscienceAustralia/PyRate#192]
Check the "pthr" parameter for realistic values in config file. "pthr" is a parameter used in both time series and linrate algorithms (but separately assigned for the two algorithms). It is a threshold for accepting epochal observations for a pixel. Therefore the value of pthr should not exceed the number of epochs in the interferogram network.

A simple test could check if pthr is <= nepochs. If pthr>nepochs, then reassign pthr==nepochs and print an information statement

**Comment by mcgarth** [comment]
Similar checks might be sensible for other input parameters - to be determined

**Comment by sheecegardezi** [comment]
The input value for ts_pthr aka TIME_SERIES_PTHRESH will be checked to be within range [1,1000]
https://github.com/GeoscienceAustralia/PyRate/commit/1bf7e2c371b4f46c86619e9adde3e7b4bb4d5ad8

**Comment by mcgarth** [comment]
Hi @sheecegardezi . Is there also a similar check for the pthr parameter (aka LR_PTHRESH)?

**Comment by sheecegardezi** [comment]
Yep, ts_pthr has following checks: 

        "DataType": int,
        "DefaultValue": 3,
        "MinValue": 1,
        "MaxValue": 1000
