### ISSUE TITLE
Determine what the interface to the system looks like.

### ISSUE THREAD

**Issue by gasuperdev** [GeoscienceAustralia/PyRate#21]
We presently have a different script for each piece of processing. This is largely due to historical reasons and now we have moved to luigi is unecessary (though it may still be desirable).

Now that we are using luigi, the implementation of the scripts is extremely similar (basically identical) and hence we can move to a system where we have one script and we specify what the action to perform is. This is supported directly by luigi and all we really need to do is start using `luigi.run` rather than `luigi.build`.

This needs some discussion

**Comment by mcgarth** [comment]
closing... current interface (in use in commit https://github.com/GeoscienceAustralia/PyRate/commit/216559a65fc3c6bec8b197315939d47d61a2f604) using 'compiled' pyrate is working cleanly
