### ISSUE TITLE
prepifg.dem_or_ifg always returns DEM 

### ISSUE THREAD

**Issue by brenmous** [GeoscienceAustralia/PyRate#213]
There's a function `prepifg.dem_or_ifg(data_path)` that returns an `Ifg` or `DEM` object. It checks if the gdal dataset metadata contains a "DATE" key - if this is true, then it returns an `Ifg` instantiated from the file, if false then a `DEM`. It's used frequently throughout the prepifg process.

As far as I can tell, IFG metadata doesn't contain a "DATE" key - refer to ifgconstants.py. Changing this to check for "MASTER_DATE" (which does appear in Ifg metadata and not DEM metadata) correctly returns Ifg objects for interferogram files.

This appears to have been happening for a while and the software is still operational. We need to work out the impact of this bug, if any, and if making the above change has an impact. It seems like a big deal as the `Ifg` class contains a lot more data than the `DEM` class, which is a single band raster. Prepifg still returns `Ifg`s as a final product, so maybe the conversion is being correctly done later? I'll update here as I find out more.

**Comment by brenmous** [comment]
@mcgarth @tfuhrmann it also needs to be noted that it correctly returns `DEM` object for DEM files, but also creates a `DEM` object for GAMMA incidence files - is it correct that incidence files should be treated as `DEM` objects?

**Comment by mcgarth** [comment]
No they should not be treated the same, but:
- In the case of GAMMA-format input files, a DEM and an incidence angle file appear the same - both big-endian float32 flat binary files.
- There is an Incidence class in shared.py 'earmarked' for incidence files, but it is not fully developed.
- At the moment neither DEM or incidence are used by any PyRate functions. We should discuss how we want to use these auxiliary data (DEM, incidence) with new features/algorithms going forward.

**Comment by sheecegardezi** [comment]
- Both class Ifg and class DEM are children of class RasterBase. In all the subsequest usages 2 common properties are being accessed i.e. band and metadata. Band data is subsampled and written to a new file along with the metadata.
- Change has already been made to differnate DEM and Ifg based on MASTER_DATE. 
- It is proposed to use Rasterio in the future and source properties of dataset directly rather then having custom classes.

![usages](https://user-images.githubusercontent.com/7543039/74804414-4fc5f680-5334-11ea-8295-8d4cdc07579a.PNG)
