### ISSUE TITLE
Warning 6: driver MEM does not support creation option compress

### ISSUE THREAD

**Issue by mcgarth** [GeoscienceAustralia/PyRate#217]
Working with code at https://github.com/GeoscienceAustralia/PyRate/commit/ea06bf0ba5a8b61d67cc1e95cd8b8765a75b6a40, get the following screen output whilst running mpirun -n 28 pyrate process input_parameters.conf:

```
+20s pyrate.scripts.run_pyrate:INFO Calculating orbfit correction
+20s pyrate.scripts.run_pyrate:INFO Checking Orbital error correction status
+20s pyrate.shared:INFO Calculating corrections
Warning 6: driver MEM does not support creation option compress
Warning 6: driver MEM does not support creation option compress
Warning 6: driver MEM does not support creation option compress
```
131 Warnings are given - one per input interferogram file.

Need to remove packbits compression from in-memory GDAL driver call?

**Comment by brenmous** [comment]
This is due to changes I've made, I'll take a look.
