### ISSUE TITLE
Automatic tiling when using mpirun

### ISSUE THREAD

**Issue by mcgarth** [GeoscienceAustralia/PyRate#218]
If the 'process' stage is run with `mpirun -n #`, then automatically calculate how to tile up the problem, rather than requiring user to specify the number of tiles (and tile row/col configuration) using -r and -c flags.

**Comment by sheecegardezi** [comment]
This feature has been implemented. 
https://github.com/GeoscienceAustralia/PyRate/commit/80321a77b439ec77f2ec9ac734bc495deaca7606
