### ISSUE TITLE
Enhancement: Introduce Change Detection in Bi-temporal Polarimetric SAR Images

### ISSUE THREAD

**Issue by jjerphan** [GeoscienceAustralia/PyRate#277]
**Is your feature request related to a problem? Please describe.**
It is not related to a problem in the PyRate but a proposal.

@h-sdl and I have implemented a small pipeline for change detection for polarimetric SAR images in python from [1].

In short, we can detect changes between two SAR and subclasses changes in the two images:

![Example 1](https://gitlab.com/jjerphan/rsd-project/-/raw/master/figs/Redon_res.png) 
![Example 2](https://gitlab.com/jjerphan/rsd-project/-/raw/master/figs/Sajnam_res.png)

**Describe the solution you'd like**
The best would be to known whether such a feature would be interesting to include in PyRate.

**Describe alternatives you've considered**
We do not know this library that much and thus this needs discussions. 😊

**Additional context**
See our repository of the implementation: https://gitlab.com/jjerphan/rsd-project

See this original proposal of the method:
[1] Advanced Methods for Change Detection in Multi-polarization and
Very-High Resolution Multitemporal SAR Images. Davide Pirrone. PhD thesis, International Doctorate School in
Information and Communication Technologies - University of Trento, 1 2019.

See the slides of the presentation of this method we made (in French): https://cloud.mines-paristech.fr/index.php/s/aXhZ2o5BM8fIBR0

**Comment by mcgarth** [comment]
Hi @jjerphan  and thanks a lot for your proposal! We've had a look at your repository and algorithm and unfortunately do not think it is a good fit to PyRate. The aim of PyRate is to deduce the displacement time series from a stack of SAR phase interferograms. We use interferometric coherence as a secondary input but we are not using SAR backscatter intensity at all at the moment and we do not consider the different polarimetric channels (it is assumed all input interferograms have the same polarisation). 
I think the PyRAT library might be a better fit for your contribution, see https://github.com/birgander2/PyRAT 
Thanks again for getting in touch!

**Comment by jjerphan** [comment]
Hi @mcgarth !

Thank you for this comprehensive answer! We just have proposed this contribution to PyRAT, as you suggested, here: 
https://github.com/birgander2/PyRAT/issues/25
