### ISSUE TITLE
Remove unused stuff from conf.py

### ISSUE THREAD

**Issue by gasuperdev** [GeoscienceAustralia/PyRate#30]
When we use luigi to manage the config, the config parsing is done for us. There are some utilities in _pyrate/conf.py_ that could hence potentially be removed. I did not do so because I was not sure if there was some reason to keep them, but you might want to in the future.

**Comment by mcgarth** [comment]
to be considered during the upcoming clean up @basaks ?

**Comment by basaks** [comment]
We don't default to luigi anymore, so this is not relevant.
