### ISSUE TITLE
Simulating Light Pipes - Is it possible?

### ISSUE THREAD

**Issue by leoheck** [GeoscienceAustralia/PyRate#322]
This is just a usability question.

I want to simulate a light pipe where I am transferring light from one place of my product to another using a transparent pipe which is a complex shape not a cylinder, for instance.

Basically, I want to simulate how and how much light is going to move from an LED source to the external interface of my product. I want to design this light pipe to achieve a good light intensity and also a solid light pattern. 

So, my question is: 

Is possible to do such a simulation using PyRat and Freecad?
If the answer is yes, 

1. How can I achieve that, do you have any tutorials or examples?

2. I have a 3d model of my light pipe made with the Part Design tool, can I use this or I have to recreate it?

**Comment by mcgarth** [comment]
Hi @leoheck! Did you intend your question for the _PyRat_ repository? https://github.com/birgander2/PyRAT

The problem you are describing is not possible with _PyRate_ (this repo), but I hope you find a workable solution!

**Comment by leoheck** [comment]
Oh, I found this PyRate workspace on the Freecad plugins list, and also someone in the Freecad forum has mentioned it.
Thanks for answering my question and for mentioning the PyRat. I didn't knew about it.
