### ISSUE TITLE
Error Handling: error raise message is incorrect

### ISSUE THREAD

**Issue by adeane-ga** [GeoscienceAustralia/PyRate#362]
**Very simple problem and fix**
Line 315 of `prepifg_helper.py` has an error exception message that states the wrong case.

https://github.com/GeoscienceAustralia/PyRate/blob/8203989e7d9b675491e79610cff04728d8dc3973/pyrate/core/prepifg_helper.py#L314-L317

Should state:

`ifgxfirst must be less than ifgxlast`

**Comment by adu461386118** [comment]
agree, ifgxfirst and ifgxlast are two longitude values, ifgxfirst should be smaller than ifgxlast,

**Comment by adeane-ga** [comment]
Closing this issue because it was fixed with this merge into develop: https://github.com/GeoscienceAustralia/PyRate/pull/369

Thanks.
