### ISSUE TITLE
Save intermediate files at every correction step

### ISSUE THREAD

**Issue by basaks** [GeoscienceAustralia/PyRate#51]
save before and after
- orbital correction
- APS correction

**Comment by mcgarth** [comment]
In version 0.2.0 d0a634b the orbital, APS and reference phase corrections are done only if they have not been done before (Ifg geotiff metadata is interrogated) and the update Ifg phase data is saved to disk, overwriting previous files.

**Comment by tfuhrmann** [comment]
To be discussed in the next Sprint Planning. My opinion:
- output the corrections as tif-files/npy-arrays after they have been calculated (this helps to user to assess whether the correction values are reasonable)
- overwrite these outputs in case corrections are re-calculated with different parameters
- keep uncorrected phase of interferogram on disk
- apply the corrections to uncorrected interferogram and save as new corrected file on disk

**Comment by nhsamrat** [comment]
I think it will be convenient for the users if every correction step divide into sub-division under the process step (e.g. process 1: orbital correction, process 2: line rate estimation and so on). Then user can quickly jump into their specific required step to see the output and processing algorithm of that step.

**Comment by mcgarth** [comment]
- output the corrections as tif-files/npy-arrays after they have been calculated (this helps to user to assess whether the correction values are reasonable)

My view is that these should all be saved as tifs rather than numpy arrays, because compression can be applied, thus saving disk space.

**Comment by mcgarth** [comment]
I like the idea of @nhsamrat . The future workflow could look something like:
conv2tif - prepifg - correct - timeseries - linrate - merge
with timeseries and linrate being each optional

**Comment by mcgarth** [comment]
> I like the idea of @nhsamrat . The future workflow could look something like:
> conv2tif - prepifg - correct - timeseries - linrate - merge
> with timeseries and linrate being each optional

This was implemented in https://github.com/GeoscienceAustralia/PyRate/pull/295

> output the corrections as tif-files/npy-arrays after they have been calculated (this helps to user to assess whether the correction values are reasonable)
> My view is that these should all be saved as tifs rather than numpy arrays, because compression can be applied, thus saving disk space.

numpy array saving of corrections was implemented in  https://github.com/GeoscienceAustralia/PyRate/pull/295
