### ISSUE TITLE
Write prepifg matllab equality tests for various crop options and looks (resolution)

### ISSUE THREAD

**Issue by basaks** [GeoscienceAustralia/PyRate#59]
...to make sure that we have reproduced matlab results for various prepifg parameter combinations.

**Comment by basaks** [comment]
We use `gdal.GRA_Average` to multilook. There is a `pirate` specific `gdal.GRA_NearestNeighbour` multilooking option in `PyRate` to match `pirate` `prepifg` output.

**Comment by basaks** [comment]
@mcgarth to decide.

**Comment by mcgarth** [comment]
Not required
