### ISSUE TITLE
recent windows errors

### ISSUE THREAD

**Issue by gp8899** [GeoscienceAustralia/PyRate#70]
i'm getting alot of:
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: 'c:\users\u43382\appdata\local\temp\6\tmpgblmbb.tif'

is anyone else getting these error when running on windows? pretty sure my environment is up to date.

[errors_win.txt](https://github.com/GeoscienceAustralia/PyRate/files/258299/errors_win.txt)

**Comment by basaks** [comment]
Parked for now as Windows is not supported yet.
