### ISSUE TITLE
Parallelise the network orbit correction

### ISSUE THREAD

**Issue by basaks** [GeoscienceAustralia/PyRate#75]
Implement mpi and multiprocessing for network orbital correction to improve efficiency for large interferogram networks and low `orbfitlksx` and `orbfitlksy` values

**Comment by basaks** [comment]
Log info of multilooked interferrogram total memory requirement.
Test and fall back to `independent method` when memory requirement not satisfied.

**Comment by basaks** [comment]
Orbital fit method 1(independent method) is now mpi parallel.
Orbital fit method 2 (network method) is not parallel and way forward is captured in  #147.

@mcgarth to decide future development.

**Comment by mcgarth** [comment]
MPI/parallel network orb method to be implemented if testing reveals a bottleneck

**Comment by mcgarth** [comment]
Closing, the issue is too old and need is not high priority
