### ISSUE TITLE
NCI jobs will need outside network access for running PyAPS algorithm

### ISSUE THREAD

**Issue by mcgarth** [GeoscienceAustralia/PyRate#76]
This is a pre-emptive issue for when PyAPS is being run in batch jobs at the NCI.

Only certain NCI back-end nodes can access an outside network for downloading data. These nodes will need to be used to download the ECMWF files for use with PyAPS. I believe the nodes to be used are part of the 'copyq' - but @lawrie26 should be able to confirm.

**Comment by basaks** [comment]
Parked for now as we are not implementing weather model now.
