### ISSUE TITLE
BUG: LUIGI option does not process DEMs

### ISSUE THREAD

**Issue by basaks** [GeoscienceAustralia/PyRate#88]

**Comment by mcgarth** [comment]
...mothball the luigi capability for the current version?

**Comment by basaks** [comment]
Fix broken LUIGI prepifg.

**Comment by mcgarth** [comment]
confirmed for both GAMMA and ROI_PAC input.
incidence/elevation files also not converted.

**Comment by basaks** [comment]
LUIGI support was moved lower in priority. We should pick this one up at a later date.

**Comment by sheecegardezi** [comment]
Dependacy removed.
