### ISSUE TITLE
Enhancement: Convert from LOS using incidence angles

### ISSUE THREAD

**Issue by mcgarth** [GeoscienceAustralia/PyRate#9]
Use incidence angle maps to convert from line of sight to vertical (or horizontal). This is particularly important if interferograms from ascending and descending geometry are to be jointly inverted (see Wang et al GJI 2012)

**Comment by basaks** [comment]
We have a `shared.Incidence` class that can be used here.
We have an implementation of `incidence` angle for `gamma` in `prepifg`.

**Comment by sheecegardezi** [comment]
https://agupubs.onlinelibrary.wiley.com/doi/pdf/10.1029/2012GL051222

**Comment by mcgarth** [comment]
The paper I mentioned in the first comment is this one: https://academic.oup.com/gji/article/191/3/1119/558777

**Comment by mcgarth** [comment]
Since https://github.com/GeoscienceAustralia/PyRate/pull/302, PyRate now calculates incidence angles based on baselines, geocoding look-up table and other metadata.

The enhancement here will use the new incidence angles calculated by PyRate and saved as geotiff

**Comment by mcgarth** [comment]
This functionality is implemented in https://github.com/GeoscienceAustralia/PyRate/pull/321

This issue will be closed once the PR is approved and merged
