### ISSUE TITLE
Enhancement: Add config file contents to runtime log file

### ISSUE THREAD

**Issue by mcgarth** [GeoscienceAustralia/PyRate#94]
In order to capture the provenance of each run, copy the pyrate.conf file contents verbatim to the top of the PyRate log file generated at each run instance.

**Comment by basaks** [comment]
Json dump config in log steam?

**Comment by mcgarth** [comment]
Sounds good. How would this look in practice? A few lines of text in the screen output?

**Comment by basaks** [comment]
See # 506ef4f958b01f27acc322bd4741ad0c92fd2a3e.

> (pyrate) PyRate:aps$ pyrate prepifg configs/pyrate_gamma.conf 
> +1s pyrate.scripts.main:INFO This job was run with the following parameters:
> +1s pyrate.scripts.main:INFO {
>     "APS_ELEVATION_EXT": null,
>     "APS_INCIDENCE_EXT": null,
>     "apscorrect": 0,
>     "apsest": 1,
>      ...
>     "ts_pthr": 10,
>     "tscal": 1,
>     "tsmethod": 1,
>     "use_luigi": 0
> }
> +1s pyrate.scripts.run_prepifg:INFO Preparing GAMMA format interferograms
> +1s pyrate.scripts.run_prepifg:INFO Running prepifg in serial
> +1s pyrate.scripts.run_prepifg:INFO Finished prepifg

**Comment by mcgarth** [comment]
A log file can be saved by the user by redirecting screen output to a file if desired, e.g.:

```pyrate prepifg pyrate_gamma.conf > log.file```
